package com.example.sosemergency.entities;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import com.example.sosemergency.DataLoader.ContactDatabaseContract;
/*
 *
 * This class represents the Contact entity in the Room database. It is annotated with
 * @Entity to indicate that it is a database entity, and it includes information about
 * the table name in the database.
 *
 * @Entity annotation parameters:
 *   tableName - The name of the "contacts" table in the database.
 *
 * Fields:
 *   - id: The primary key for the contact, auto-generated by Room.
 *   - name: The name of the contact.
 *   - phoneNumber: The phone number of the contact.
 *
 */
@Entity(tableName = ContactDatabaseContract.ContactEntry.TABLE_NAME)
public class Contact {

    @PrimaryKey(autoGenerate = true)
    public long id;

    public String name;
    public String phoneNumber;

    /*
     * Constructor to create a new Contact instance.
     *
     * @param name - The name of the contact.
     * @param phoneNumber - The phone number of the contact.
     */
    public Contact(String name, String phoneNumber) {
        this.name = name;
        this.phoneNumber = phoneNumber;
    }

    /*
     * Getter method for the contact's ID.
     *
     * @return long - The ID of the contact.
     */
    public long getId() {
        return id;
    }

    /*
     * Setter method for the contact's ID.
     *
     * @param id - The ID to set for the contact.
     */
    public void setId(long id) {
        this.id = id;
    }

    /*
     * Getter method for the contact's name.
     *
     * @return String - The name of the contact.
     */
    public String getName() {
        return name;
    }

    /*
     * Setter method for the contact's name.
     *
     * @param name - The name to set for the contact.
     */
    public void setName(String name) {
        this.name = name;
    }

    /*
     * Getter method for the contact's phone number.
     *
     * @return String - The phone number of the contact.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /*
     * Setter method for the contact's phone number.
     *
     * @param phoneNumber - The phone number to set for the contact.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /*
     * Overrides the default toString method to provide a string representation
     * of the Contact object for easy debugging.
     *
     * @return String - The string representation of the Contact object.
     */
    @Override
    public String toString() {
        return "Contact{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                '}';
    }
}
